In [2]:

import torch

# 1. 创建张量


In [3]:
## 1.1 arange

In [4]:
x=torch.arange(20)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [5]:
x.shape

torch.Size([20])

In [6]:
xsize=x.numel()
xsize

20

### 1.2 多维tensor

In [7]:
y=torch.tensor([
    [11,12,13,14],
    [21,22,23,24],
    [31,32,33,34]
])
y

tensor([[11, 12, 13, 14],
        [21, 22, 23, 24],
        [31, 32, 33, 34]])

In [8]:
y.shape

torch.Size([3, 4])

In [9]:
ysize=y.numel()
ysize

12

In [10]:
tmp=x.reshape(4,5)
tmp

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [11]:
tmp=y.reshape(-1)
tmp

tensor([11, 12, 13, 14, 21, 22, 23, 24, 31, 32, 33, 34])

In [12]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
torch.zeros((3, 2, 3))

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [14]:
torch.ones((3,2,3))

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [15]:
x=torch.tensor([1.0,2.5,3,10.5])
y=torch.tensor([2.0,3.0,4.0,5.0])
x+y,y-x,y*x

(tensor([ 3.0000,  5.5000,  7.0000, 15.5000]),
 tensor([ 1.0000,  0.5000,  1.0000, -5.5000]),
 tensor([ 2.0000,  7.5000, 12.0000, 52.5000]))

In [16]:
x=torch.tensor([2.0,2,2,2],dtype=torch.float32)
y=torch.tensor([2.0,3.0,4.0,5.0])
x**y,y/x

(tensor([ 4.,  8., 16., 32.]), tensor([1.0000, 1.5000, 2.0000, 2.5000]))

In [17]:
x=torch.tensor([0,2,2,2],dtype=torch.float32)
torch.exp(x)

tensor([1.0000, 7.3891, 7.3891, 7.3891])

In [19]:
x=torch.arange(12,dtype=torch.float32).reshape((3,4))
y=torch.tensor([
    [11,12,13,14],
    [21,22,23,24],
    [31,32,33,34]
],dtype=torch.float32)
x,y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[11., 12., 13., 14.],
         [21., 22., 23., 24.],
         [31., 32., 33., 34.]]))

In [24]:
torch.cat((x,y),dim=0),torch.cat((x,y),dim=-1),torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [11., 12., 13., 14.],
         [21., 22., 23., 24.],
         [31., 32., 33., 34.]]),
 tensor([[ 0.,  1.,  2.,  3., 11., 12., 13., 14.],
         [ 4.,  5.,  6.,  7., 21., 22., 23., 24.],
         [ 8.,  9., 10., 11., 31., 32., 33., 34.]]),
 tensor([[ 0.,  1.,  2.,  3., 11., 12., 13., 14.],
         [ 4.,  5.,  6.,  7., 21., 22., 23., 24.],
         [ 8.,  9., 10., 11., 31., 32., 33., 34.]]))

In [26]:
x=torch.ones((3,4,5))
y=torch.zeros((3,4,5))
x,y

(tensor([[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]),
 tensor([[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]))

In [32]:
help(torch.ones)

Help on built-in function ones:

ones(...)
    ones(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Returns a tensor filled with the scalar value `1`, with the shape defined
    by the variable argument :attr:`size`.
    
    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.
    
    Keyword arguments:
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
        layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
            Default: ``torch.strided``.
        device (:class:`torch.device`, optional): the desired device of returned tensor.
            Default: if ``None``, uses the cur

In [34]:
x=torch.ones((3,4))
y=torch.zeros((3,4))
x==y,torch.sum(x)

(tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor(12.))