In [68]:
import torch


In [69]:
x=torch.arange(4,dtype=torch.float32)
y=torch.ones(4,dtype=torch.float32)
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
x,y,A

(tensor([0., 1., 2., 3.]),
 tensor([1., 1., 1., 1.]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]))

# 向量的点积
x的转置乘以y

In [70]:
x*y,torch.dot(x,y),torch.sum(x*y)

(tensor([0., 1., 2., 3.]), tensor(6.), tensor(6.))

# 矩阵向量积

In [71]:
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

# 矩阵矩阵乘法

In [72]:
B=torch.ones(4,3)
A,B,torch.mm(A,B)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

# 范数

In [73]:
u=torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [74]:
torch.abs(u).sum()

tensor(7.)

In [75]:
C=torch.ones((9,4),dtype=torch.float32)
torch.norm(C)

tensor(6.)

In [76]:
len(C)

9

In [77]:
A=torch.arange(24).reshape(2,3,4)
len(A)

2

In [79]:
A=torch.arange(4)
A,A.reshape(4,1),A*A.reshape(4,1)

(tensor([0, 1, 2, 3]),
 tensor([[0],
         [1],
         [2],
         [3]]),
 tensor([[0, 0, 0, 0],
         [0, 1, 2, 3],
         [0, 2, 4, 6],
         [0, 3, 6, 9]]))