In [85]:
import torch

In [86]:
x = torch.arange(4.0, requires_grad=True)
x, x.grad

(tensor([0., 1., 2., 3.], requires_grad=True), None)

In [87]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [88]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [89]:
x.grad == 4 * x

tensor([True, True, True, True])

In [90]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [91]:
x.grad.zero_()
y = x * x
y.sum().backward()
x, y, x.grad

(tensor([0., 1., 2., 3.], requires_grad=True),
 tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>),
 tensor([0., 2., 4., 6.]))

In [92]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()

x.grad, x.grad == y

(tensor([0., 1., 4., 9.]), tensor([True, True, True, True]))

In [93]:
x, x.norm()

(tensor([0., 1., 2., 3.], requires_grad=True),
 tensor(3.7417, grad_fn=<CopyBackwards>))

In [94]:
x.grad.zero_()
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [95]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c


In [98]:
a = torch.randn(size=(3,1), requires_grad=True)
d = f(a)
d.sum().backward()

1. 为什么计算二阶导数比一阶导数的开销要更大？
2. 在运行反向传播函数之后，立即再次运行它，看看会发生什么。
3. 在控制流的例子中，我们计算`d`关于`a`的导数，如果将变量`a`更改为随机向量或矩阵，会发生什么？
4. 重新设计一个求控制流梯度的例子，运行并分析结果。
5. 使$f(x)=\sin(x)$，绘制$f(x)$和$\frac{df(x)}{dx}$的图像，其中后者不使用$f'(x)=\cos(x)$。