In [1]:
import torch

In [3]:
a=torch.arange(3).reshape(3,1)
b=torch.arange(2).reshape(1,2)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [4]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])