In [176]:
import torch

In [177]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [178]:
x[0]

tensor(0)

In [179]:
len(x)

4

In [180]:
x.shape

torch.Size([4])

In [181]:
A = torch.arange(20).reshape((5, 4))
A, A.T

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  4,  8, 12, 16],
         [ 1,  5,  9, 13, 17],
         [ 2,  6, 10, 14, 18],
         [ 3,  7, 11, 15, 19]]))

In [182]:
B = torch.tensor([
    [1, 2, 3],
    [2, 0, 4],
    [3, 4, 5]
])
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [183]:
A = torch.arange(20, dtype=torch.float32).reshape((5, 4))
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [184]:
B = A.clone()
B, B + A

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [185]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [186]:
a = 2
x = torch.arange(24).reshape((2, 3, 4))
x, a + x

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]))

In [187]:
a * x, (a * x).shape

(tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]),
 torch.Size([2, 3, 4]))

In [188]:
# x=torch.arange(24,dtype=torch.float32).reshape(2,3,4)
x = torch.arange(20, dtype=torch.float32).reshape(4, 5)
x.shape, x.sum()

(torch.Size([4, 5]), tensor(190.))

In [189]:
x_sum_0 = x.sum(axis=0)
x_sum_1 = x.sum(axis=1)
x, x_sum_0, x_sum_1

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 tensor([30., 34., 38., 42., 46.]),
 tensor([10., 35., 60., 85.]))

In [190]:
y = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)
y

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [191]:
y_sum_0 = y.sum(axis=0)
y_sum_1 = y.sum(axis=1)
y_sum_2 = y.sum(axis=2)
y_sum_0, y_sum_1, y_sum_2

(tensor([[12., 14., 16., 18.],
         [20., 22., 24., 26.],
         [28., 30., 32., 34.]]),
 tensor([[12., 15., 18., 21.],
         [48., 51., 54., 57.]]),
 tensor([[ 6., 22., 38.],
         [54., 70., 86.]]))

In [192]:
x.mean(), x.sum(), x.sum() / x.numel(), x.size(), len(x)

(tensor(9.5000), tensor(190.), tensor(9.5000), torch.Size([4, 5]), 4)

In [193]:
x, x.shape

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 torch.Size([4, 5]))

In [194]:
x.mean(axis=0), x.mean(axis=1), x.sum(axis=0) / x.shape[0]

(tensor([ 7.5000,  8.5000,  9.5000, 10.5000, 11.5000]),
 tensor([ 2.,  7., 12., 17.]),
 tensor([ 7.5000,  8.5000,  9.5000, 10.5000, 11.5000]))

In [195]:
x,x.sum(axis=0)

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 tensor([30., 34., 38., 42., 46.]))

In [196]:
sum_x = x.sum(axis=0,keepdims=True)
sum_x,sum_x.shape

(tensor([[30., 34., 38., 42., 46.]]), torch.Size([1, 5]))

In [197]:
x/sum_x

tensor([[0.0000, 0.0294, 0.0526, 0.0714, 0.0870],
        [0.1667, 0.1765, 0.1842, 0.1905, 0.1957],
        [0.3333, 0.3235, 0.3158, 0.3095, 0.3043],
        [0.5000, 0.4706, 0.4474, 0.4286, 0.4130]])

In [198]:
x

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

In [200]:
x.cumsum(axis=0),x.cumsum(axis=0).shape,x.shape

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  7.,  9., 11., 13.],
         [15., 18., 21., 24., 27.],
         [30., 34., 38., 42., 46.]]),
 torch.Size([4, 5]),
 torch.Size([4, 5]))