In [137]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, num_examples=1000)
features, labels

(tensor([[ 0.6558,  1.1776],
         [ 0.5453, -0.6602],
         [-0.7235, -1.6744],
         ...,
         [ 0.8643,  0.0695],
         [-1.7529, -0.5282],
         [-1.6814,  0.0770]]),
 tensor([[ 1.5169e+00],
         [ 7.5409e+00],
         [ 8.4495e+00],
         [ 8.2865e+00],
         [ 1.6467e-01],
         [ 1.9602e+00],
         [ 5.5814e+00],
         [ 1.2395e+00],
         [ 5.0065e+00],
         [-1.2883e+00],
         [ 7.9212e+00],
         [ 2.1357e+00],
         [-1.9703e+00],
         [ 5.9371e+00],
         [ 5.5377e+00],
         [ 6.7271e+00],
         [ 7.0188e-01],
         [ 1.6811e+00],
         [ 6.4392e+00],
         [ 5.2207e+00],
         [-1.7960e+00],
         [-1.4944e+00],
         [-1.4670e+00],
         [ 7.6609e+00],
         [ 6.8354e+00],
         [ 8.9682e+00],
         [ 2.2958e+00],
         [-9.4130e-01],
         [-2.5903e+00],
         [ 1.9663e+00],
         [-4.3621e-01],
         [ 6.3268e+00],
         [ 8.0048e+00],
         [ 1.9507e

In [138]:
def load_array(data_arrays, batch_size, is_train=True):
    data_set = data.TensorDataset(*data_arrays)
    return data.DataLoader(data_set, batch_size, shuffle=is_train)


batch_size = 10
data_iter = load_array((features, labels), batch_size)

next(iter(data_iter))

[tensor([[-0.1535,  0.2016],
         [-0.8164, -2.2570],
         [ 1.6364, -1.1832],
         [ 0.1943,  0.7136],
         [ 0.8643,  0.0695],
         [-1.8159, -1.1698],
         [-0.3979,  0.3897],
         [ 0.6055, -0.6179],
         [ 0.1168, -1.1477],
         [-0.5527,  0.6920]]),
 tensor([[ 3.1983],
         [10.2415],
         [11.4964],
         [ 2.1657],
         [ 5.7128],
         [ 4.5447],
         [ 2.0791],
         [ 7.5017],
         [ 8.3435],
         [ 0.7595]])]

In [139]:
from torch import nn

net = nn.Sequential(nn.Linear(2, 1))


In [140]:
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [141]:
loss = nn.MSELoss()

In [142]:
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

In [143]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1},loss {l:f}')

epoch 1,loss 0.000202
epoch 2,loss 0.000107
epoch 3,loss 0.000107
